name: IPFS Push

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Repo files sync]
    types:
      - completed

jobs:
  IpfsPush:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Pin files on IPFS
        run: ipfs add -r files > cid-filename.txt
        
      - name: Format result file and log pinning step results
        run: |
          sed -i 's/added //g' cid-filename.txt
          sed -i "1iLast sync: $(date)\n" cid-filename.txt
          cat cid-filename.txt
        
      - name: Commit cid-filename mapping file
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add cid-filename.txt
          git commit -m 'Sync CID-filename mapping file'
          
      - name: Push cid-filename mapping file
        uses: ad-m/github-push-action@master
