name: Repo files sync
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  RepoFilesSync:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      
      - name: Read file paths
        run: |
          mkdir external-repos
          ls
          readarray -t routeArray < files-to-sync.txt
          for route in "${routeArray[@]}";
            do urlArray=(`echo $route | tr '/' ' '`)
            repoUrl="${urlArray[0]}//${urlArray[1]}/${urlArray[2]}/${urlArray[3]}"
            ls
            cd external-repos
            echo "Hello"
            ls
            git clone $repoUrl;
          done
