name: Repo files sync
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  RepoFilesSync:
    runs-on: self-hosted
    strategy:
      matrix:
        route: |
          readarray -t routeArray < files-to-sync.txt
          routeArray
    steps:
      - uses: actions/checkout@v3
      
      - name: Read file paths
        run: echo ${{ matrix.route }}
        
      
