name: Repo files sync
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  RepoFilesSync:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      
      - name: Read file paths
        run: ls
        
      
